question_data = [
{"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
 "question": "In the game 'Until Dawn' Emily is the only playable character who can be killed by another playable character directly.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
 "question": "The commercial UK channel ITV stands for &quot;International Television&quot;.",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
 "question": "The Sniper&#039;s SMG in Team Fortress 2, was originally intended to be the Scout&#039;s primary weapon.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
 "question": "The first Maxis game to feature the fictional language &quot;Simlish&quot; was The Sims (2000).",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
 "question": "Arcade Fire&#039;s &#039;The Suburbs&#039; won the Album of the Year award in the 2011 Grammys.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
 "question": "The US emergency hotline is 911 because of the September 11th terrorist attacks.",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
 "question": "The ADAM collecters in the Bioshock series are known as Little Sisters.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
 "question": "Green Day&#039;s album &#039;American Idiot&#039; is considered a &quot;punk rock opera.&quot;",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
 "question": "The word &quot;news&quot; originates from the first letters of the 4 main directions on a compass (North, East, West, South).",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"type": "boolean", "difficulty": "medium", "category": "Art",
 "question": "Vincent van Gogh cut off one of his ears.", "correct_answer": "True",
 "incorrect_answers": ["False"]}

]
